"""Generate OSS and iBOSS intent definitions and append to prompts/intents.json."""
import json
from pathlib import Path

INTENTS_FILE = Path(__file__).resolve().parent.parent / "prompts" / "intents.json"

def convert_sql(sql: str, source: str) -> str:
    """Convert Metabase [[ {{param}} ]] syntax to {param} syntax."""
    import re
    # Remove [[ ... ]] wrappers and replace {{param}} with {param}
    # First replace all {{PARAM}} or {{param}} with {param} (lowercased)
    sql = re.sub(r'\{\{(\w+)\}\}', lambda m: '{' + m.group(1).lower() + '}', sql)
    # Then remove [[ and ]] markers (they wrap optional clauses in Metabase)
    sql = re.sub(r'\[\[\s*AND\s+', 'AND ', sql)
    sql = re.sub(r'\[\[\s*', '', sql)
    sql = re.sub(r'\s*\]\]', '', sql)
    return sql

# ── OSS INTENTS ──────────────────────────────────────────────────────────────

OSS_KPI_SQL = """SELECT 
    COUNT(NO_PERMOHONAN) AS TOTAL_DOKUMEN,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'TERBIT' THEN 1 ELSE 0 END), 0) AS TOTAL_TERBIT,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'TOLAK' THEN 1 ELSE 0 END), 0) AS TOTAL_TOLAK,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'PROSES PELAKU USAHA' THEN 1 ELSE 0 END), 0) AS TOTAL_PELAKU_USAHA,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'DALAM PROSES' THEN 1 ELSE 0 END), 0) AS TOTAL_DALAM_PROSES,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'DALAM PROSES' AND HARI_SLA_TERPAKAI > BATAS_SLA_HARI THEN 1 ELSE 0 END), 0) AS TOTAL_MELEWATI_SLA
FROM US_DWH.BI_T_IZIN_OSS
WHERE 1=1
  AND {pilih_izin}
  AND {filter_tahun}
  AND {filter_bulan}
  AND {rentang_tgl_masuk}"""

OSS_GAUGE_SQL = """SELECT 
    COALESCE(
        ROUND(
            SUM(CASE WHEN KATEGORI_STATUS <> 'DALAM PROSES' THEN 1 ELSE 0 END) 
            / NULLIF(COUNT(NO_PERMOHONAN), 0), 
        4), 
    0) AS PERFORMA_PENYELESAIAN
FROM US_DWH.BI_T_IZIN_OSS
WHERE 1=1
  AND {pilih_izin}
  AND {filter_tahun}
  AND {filter_bulan}
  AND {rentang_tgl_masuk}"""

OSS_SEBARAN_JENIS_SQL = """WITH FILTERED_DATA AS (
    SELECT JENIS_IZIN, SUB_JENIS_IZIN, STATUS_TERAKHIR, KATEGORI_STATUS, NO_PERMOHONAN
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE 1=1
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
),
MODE_DETECTOR AS (
    SELECT COUNT(DISTINCT JENIS_IZIN) AS JML_IZIN_AKTIF, MAX(JENIS_IZIN) AS IZIN_TUNGGAL
    FROM FILTERED_DATA
),
GROUPED_DATA AS (
    SELECT 
        CASE 
            WHEN M.JML_IZIN_AKTIF = 1 AND M.IZIN_TUNGGAL = 'PL' THEN F.SUB_JENIS_IZIN
            ELSE F.JENIS_IZIN
        END AS SUMBU_X,
        CASE 
            WHEN M.JML_IZIN_AKTIF = 1 THEN F.STATUS_TERAKHIR
            ELSE F.KATEGORI_STATUS
        END AS LABEL_STACK_STATUS,
        COUNT(F.NO_PERMOHONAN) AS JUMLAH_DOKUMEN
    FROM FILTERED_DATA F
    CROSS JOIN MODE_DETECTOR M
    GROUP BY 
        CASE 
            WHEN M.JML_IZIN_AKTIF = 1 AND M.IZIN_TUNGGAL = 'PL' THEN F.SUB_JENIS_IZIN
            ELSE F.JENIS_IZIN
        END,
        CASE 
            WHEN M.JML_IZIN_AKTIF = 1 THEN F.STATUS_TERAKHIR
            ELSE F.KATEGORI_STATUS
        END
)
SELECT 
    SUMBU_X,
    LABEL_STACK_STATUS,
    COALESCE(JUMLAH_DOKUMEN, 0) AS JUMLAH_DOKUMEN
FROM GROUPED_DATA
ORDER BY 
    SUM(JUMLAH_DOKUMEN) OVER(PARTITION BY SUMBU_X) DESC,
    SUMBU_X ASC,
    JUMLAH_DOKUMEN DESC"""

OSS_SEBARAN_RISIKO_SQL = """WITH FILTERED_DATA AS (
    SELECT RISIKO, NO_PERMOHONAN
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE 1=1
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
)
SELECT 
    UPPER(RISIKO) AS TINGKAT_RISIKO,
    COALESCE(COUNT(NO_PERMOHONAN), 0) AS JUMLAH_DOKUMEN
FROM FILTERED_DATA
WHERE RISIKO IS NOT NULL
GROUP BY UPPER(RISIKO)
ORDER BY JUMLAH_DOKUMEN DESC"""

OSS_SEBARAN_STATUS_SQL = """WITH FILTERED_DATA AS (
    SELECT JENIS_IZIN, SUB_JENIS_IZIN, STATUS_TERAKHIR, KATEGORI_STATUS, NO_PERMOHONAN
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE 1=1
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
),
MODE_DETECTOR AS (
    SELECT 
        JENIS_IZIN, SUB_JENIS_IZIN, STATUS_TERAKHIR, KATEGORI_STATUS, NO_PERMOHONAN,
        COUNT(DISTINCT JENIS_IZIN) OVER () AS JML_IZIN_AKTIF,
        MAX(CASE WHEN JENIS_IZIN = 'PL' THEN 1 ELSE 0 END) OVER () AS HAS_PL
    FROM FILTERED_DATA
),
AGGREGATED_DATA AS (
    SELECT 
        CASE 
            WHEN JML_IZIN_AKTIF = 1 AND HAS_PL = 1 THEN SUB_JENIS_IZIN
            ELSE JENIS_IZIN
        END AS KATEGORI_IZIN,
        CASE 
            WHEN JML_IZIN_AKTIF = 1 THEN STATUS_TERAKHIR
            ELSE KATEGORI_STATUS
        END AS TARGET_STATUS,
        COUNT(NO_PERMOHONAN) AS JUMLAH
    FROM MODE_DETECTOR
    GROUP BY 
        CASE 
            WHEN JML_IZIN_AKTIF = 1 AND HAS_PL = 1 THEN SUB_JENIS_IZIN
            ELSE JENIS_IZIN
        END,
        CASE 
            WHEN JML_IZIN_AKTIF = 1 THEN STATUS_TERAKHIR
            ELSE KATEGORI_STATUS
        END
),
FINAL_FLOW AS (
    SELECT 
        'TOTAL PERMOHONAN' AS SOURCE, 
        KATEGORI_IZIN AS TARGET, 
        COALESCE(SUM(JUMLAH), 0) AS VALUE,
        1 AS FLOW_LEVEL
    FROM AGGREGATED_DATA 
    GROUP BY KATEGORI_IZIN
    UNION ALL
    SELECT 
        KATEGORI_IZIN AS SOURCE, 
        TARGET_STATUS AS TARGET, 
        COALESCE(JUMLAH, 0) AS VALUE,
        2 AS FLOW_LEVEL
    FROM AGGREGATED_DATA 
    WHERE JUMLAH > 0
)
SELECT SOURCE, TARGET, VALUE 
FROM FINAL_FLOW
ORDER BY 
    FLOW_LEVEL ASC, 
    VALUE DESC"""

OSS_TREN_INFLOW_OUTFLOW_SQL = """WITH FILTERED_DATA AS (
    SELECT 
        NO_PERMOHONAN, 
        KATEGORI_STATUS, 
        TRUNC(TGL_MASUK) AS TGL_MASUK, 
        TRUNC(TGL_STATUS_TERAKHIR) AS TGL_SELESAI
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE 1=1
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
),
ALL_DATES AS (
    SELECT TGL_MASUK AS TGL FROM FILTERED_DATA WHERE TGL_MASUK IS NOT NULL
    UNION
    SELECT TGL_SELESAI AS TGL FROM FILTERED_DATA WHERE TGL_SELESAI IS NOT NULL AND KATEGORI_STATUS = 'TERBIT'
),
INFLOW AS (
    SELECT TGL_MASUK AS TGL, COUNT(NO_PERMOHONAN) AS JML_INFLOW
    FROM FILTERED_DATA
    WHERE TGL_MASUK IS NOT NULL
    GROUP BY TGL_MASUK
),
OUTFLOW AS (
    SELECT TGL_SELESAI AS TGL, COUNT(NO_PERMOHONAN) AS JML_OUTFLOW
    FROM FILTERED_DATA
    WHERE KATEGORI_STATUS = 'TERBIT' AND TGL_SELESAI IS NOT NULL
    GROUP BY TGL_SELESAI
)
SELECT 
    D.TGL AS TANGGAL,
    COALESCE(I.JML_INFLOW, 0) AS INFLOW_PERMOHONAN,
    COALESCE(O.JML_OUTFLOW, 0) AS OUTFLOW_TERBIT
FROM ALL_DATES D
LEFT JOIN INFLOW I ON D.TGL = I.TGL
LEFT JOIN OUTFLOW O ON D.TGL = O.TGL
ORDER BY D.TGL ASC"""

OSS_FUNNEL_SQL = """WITH DATA_STATUS AS (
    SELECT UPPER(JENIS_IZIN) AS JENIS_IZIN, STATUS_TERAKHIR
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE 1=1
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
),
MODE_FUNNEL AS (
    SELECT 
        CASE WHEN COUNT(DISTINCT JENIS_IZIN) = 1 THEN MAX(JENIS_IZIN) ELSE 'UMUM' END AS TIPE_FUNNEL
    FROM DATA_STATUS
),
LEVELING AS (
    SELECT D.*, M.TIPE_FUNNEL,
        CASE 
            WHEN M.TIPE_FUNNEL = 'UMUM' THEN
                CASE 
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TERBIT%' OR UPPER(STATUS_TERAKHIR) LIKE '%DISETUJUI%' THEN 4
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%KEMBALI%' OR UPPER(STATUS_TERAKHIR) LIKE '%PEMBAYARAN%' OR UPPER(STATUS_TERAKHIR) LIKE '%PERBAIKAN%' THEN 3
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%VERIFIKASI%' OR UPPER(STATUS_TERAKHIR) LIKE '%RAPAT%' OR UPPER(STATUS_TERAKHIR) LIKE '%STAF%' OR UPPER(STATUS_TERAKHIR) LIKE '%KASIE%' OR UPPER(STATUS_TERAKHIR) LIKE '%DIREKTUR%' THEN 2
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TOLAK%' OR UPPER(STATUS_TERAKHIR) LIKE '%PENOLAKAN%' THEN 0 
                    ELSE 1 
                END
            WHEN M.TIPE_FUNNEL IN ('PB', 'PBUMKU') THEN
                CASE 
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TERBIT%' THEN 6
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%VERIFIKASI%' THEN 5
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%SURVEI%' THEN 4
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%PERSETUJUAN%' THEN 3
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%KOMITMEN%' THEN 2
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%KEMBALI%' OR UPPER(STATUS_TERAKHIR) LIKE '%TOLAK%' THEN 0 
                    ELSE 1 
                END
            WHEN M.TIPE_FUNNEL = 'PL' THEN
                CASE 
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TERBIT%' THEN 4
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%RAPAT%' THEN 3
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TEKNIS%' THEN 2
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TOLAK%' THEN 0 
                    ELSE 1 
                END
            WHEN M.TIPE_FUNNEL = 'PKKPRL' THEN
                CASE 
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TERBIT%' THEN 7
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%PERSETUJUAN%' THEN 6
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%RAPAT%' THEN 5
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%VERIFIKASI TEKNIS%' OR UPPER(STATUS_TERAKHIR) LIKE '%TEKNIS%' THEN 4
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%VERIFIKASI DOKUMEN%' THEN 3
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%SPP%' OR UPPER(STATUS_TERAKHIR) LIKE '%BAYAR%' THEN 2
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TOLAK%' OR UPPER(STATUS_TERAKHIR) LIKE '%PENOLAKAN%' THEN 0 
                    ELSE 1 
                END
            WHEN M.TIPE_FUNNEL = 'PPKH' THEN
                CASE 
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TERBIT%' THEN 5
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%DIREKTUR%' THEN 4
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%KASIE%' THEN 3
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%STAF%' THEN 2
                    WHEN UPPER(STATUS_TERAKHIR) LIKE '%TOLAK%' OR UPPER(STATUS_TERAKHIR) LIKE '%PENOLAKAN%' THEN 0 
                    ELSE 1 
                END
        END AS LVL
    FROM DATA_STATUS D
    CROSS JOIN MODE_FUNNEL M
),
CUMULATIVE AS (
    SELECT 1 AS LVL_ID, COUNT(*) AS JUMLAH FROM LEVELING UNION ALL
    SELECT 2, COUNT(*) FROM LEVELING WHERE LVL >= 2 UNION ALL
    SELECT 3, COUNT(*) FROM LEVELING WHERE LVL >= 3 UNION ALL
    SELECT 4, COUNT(*) FROM LEVELING WHERE LVL >= 4 UNION ALL
    SELECT 5, COUNT(*) FROM LEVELING WHERE LVL >= 5 UNION ALL
    SELECT 6, COUNT(*) FROM LEVELING WHERE LVL >= 6 UNION ALL
    SELECT 7, COUNT(*) FROM LEVELING WHERE LVL >= 7
),
LABELS AS (
    SELECT 'UMUM' AS TIPE, 1 AS LVL_ID, '1. Dokumen Masuk' AS LABEL FROM DUAL UNION ALL
    SELECT 'UMUM', 2, '2. Dalam Proses' FROM DUAL UNION ALL
    SELECT 'UMUM', 3, '3. Proses Pelaku Usaha' FROM DUAL UNION ALL
    SELECT 'UMUM', 4, '4. Terbit' FROM DUAL UNION ALL
    SELECT 'PB', 1, '1. Permohonan' FROM DUAL UNION ALL
    SELECT 'PB', 2, '2. Pemenuhan Komitmen' FROM DUAL UNION ALL
    SELECT 'PB', 3, '3. Persetujuan' FROM DUAL UNION ALL
    SELECT 'PB', 4, '4. Survei' FROM DUAL UNION ALL
    SELECT 'PB', 5, '5. Verifikasi' FROM DUAL UNION ALL
    SELECT 'PB', 6, '6. Terbit' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 1, '1. Permohonan' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 2, '2. Pemenuhan Komitmen' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 3, '3. Persetujuan' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 4, '4. Survei' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 5, '5. Verifikasi' FROM DUAL UNION ALL
    SELECT 'PBUMKU', 6, '6. Terbit' FROM DUAL UNION ALL
    SELECT 'PL', 1, '1. Permohonan' FROM DUAL UNION ALL
    SELECT 'PL', 2, '2. Verifikasi Teknis' FROM DUAL UNION ALL
    SELECT 'PL', 3, '3. Rapat Pimpinan' FROM DUAL UNION ALL
    SELECT 'PL', 4, '4. Terbit' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 1, '1. Permohonan Masuk' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 2, '2. Pelunasan SPP' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 3, '3. Verifikasi Dokumen' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 4, '4. Verifikasi Teknis' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 5, '5. Rapat Pimpinan' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 6, '6. Persetujuan KKPRL' FROM DUAL UNION ALL
    SELECT 'PKKPRL', 7, '7. Terbit' FROM DUAL UNION ALL
    SELECT 'PPKH', 1, '1. Permohonan Masuk' FROM DUAL UNION ALL
    SELECT 'PPKH', 2, '2. Staf Pemroses' FROM DUAL UNION ALL
    SELECT 'PPKH', 3, '3. Kasie Pemroses' FROM DUAL UNION ALL
    SELECT 'PPKH', 4, '4. Direktur PPKH' FROM DUAL UNION ALL
    SELECT 'PPKH', 5, '5. Terbit' FROM DUAL
)
SELECT L.LABEL AS TAHAPAN, COALESCE(C.JUMLAH, 0) AS JUMLAH 
FROM CUMULATIVE C
CROSS JOIN MODE_FUNNEL M
JOIN LABELS L ON C.LVL_ID = L.LVL_ID AND L.TIPE = M.TIPE_FUNNEL
WHERE L.LABEL IS NOT NULL
ORDER BY L.LVL_ID"""

OSS_SLA_SQL = """SELECT 
    COALESCE(
        ROUND(
            SUM(CASE WHEN HARI_SLA_TERPAKAI <= BATAS_SLA_HARI THEN 1 ELSE 0 END) 
            / NULLIF(COUNT(NO_PERMOHONAN), 0), 
        4), 
    0) AS KEPATUHAN_SLA
FROM US_DWH.BI_T_IZIN_OSS
WHERE KATEGORI_STATUS <> 'PROSES PELAKU USAHA'
  AND {pilih_izin}
  AND {filter_tahun}
  AND {filter_bulan}
  AND {rentang_tgl_masuk}"""

OSS_LEADERBOARD_SLA_SQL = """SELECT 
    NVL(VERIFIKATOR, 'TOTAL KESELURUHAN') AS NAMA,
    NVL(JABATAN_VERIFIKATOR, '-') AS JABATAN, 
    NVL(UPPER(JENIS_IZIN), '-') AS JENIS_IZIN,
    COALESCE(COUNT(NO_PERMOHONAN), 0) AS TOTAL_DOKUMEN,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'DALAM PROSES' THEN 1 ELSE 0 END), 0) AS TOTAL_DOKUMEN_AKTIF,
    COALESCE(ROUND(AVG(HARI_SLA_TERPAKAI), 1), 0) AS RATA_RATA_HARI_PROSES,
    COALESCE(SUM(CASE WHEN HARI_SLA_TERPAKAI <= BATAS_SLA_HARI THEN 1 ELSE 0 END), 0) AS JUMLAH_SESUAI_SLA,
    COALESCE(SUM(CASE WHEN KATEGORI_STATUS = 'DALAM PROSES' AND HARI_SLA_TERPAKAI > BATAS_SLA_HARI THEN 1 ELSE 0 END), 0) AS JUMLAH_LEWAT_SLA
FROM US_DWH.BI_T_IZIN_OSS
WHERE VERIFIKATOR IS NOT NULL
  AND {pilih_izin}
  AND {filter_tahun}
  AND {filter_bulan}
  AND {rentang_tgl_masuk}
GROUP BY ROLLUP((VERIFIKATOR, JABATAN_VERIFIKATOR, UPPER(JENIS_IZIN)))
ORDER BY 
    CASE WHEN VERIFIKATOR IS NULL THEN 1 ELSE 0 END ASC,
    JUMLAH_LEWAT_SLA DESC, 
    TOTAL_DOKUMEN_AKTIF DESC, 
    NAMA ASC"""

OSS_RAPOR_STAF_SQL = """WITH STATS_STAF AS (
    SELECT 
        UPPER(TRIM(VERIFIKATOR)) AS NAMA_STAF,
        COUNT(NO_PERMOHONAN) AS TOTAL_KERJA,
        SUM(CASE WHEN KATEGORI_STATUS <> 'DALAM PROSES' THEN 1 ELSE 0 END) AS TOTAL_LOLOS,
        SUM(CASE WHEN TO_CHAR(TGL_STATUS_TERAKHIR, 'HH24') = '00' OR TO_CHAR(TGL_STATUS_TERAKHIR, 'HH24MI') BETWEEN '0800' AND '1630' THEN 1 ELSE 0 END) AS TOTAL_DALAM_JAM_KERJA,
        SUM(CASE WHEN STATUS_PENCAPAIAN_SLA = 'SESUAI SLA' THEN 1 ELSE 0 END) AS TOTAL_MEMENUHI_SLA
    FROM US_DWH.BI_T_IZIN_OSS
    WHERE VERIFIKATOR IS NOT NULL
      AND (UPPER(JABATAN_VERIFIKATOR) LIKE '%VERIFIKATOR%' OR UPPER(JABATAN_VERIFIKATOR) LIKE '%STAF%')
      AND {pilih_izin}
      AND {filter_tahun}
      AND {filter_bulan}
      AND {rentang_tgl_masuk}
    GROUP BY UPPER(TRIM(VERIFIKATOR))
)
SELECT 
    NAMA_STAF AS NAMA_STAF,
    COALESCE(ROUND(
        (0.4 * (TOTAL_LOLOS / NULLIF(TOTAL_KERJA, 0)) * 100) + 
        (0.3 * (TOTAL_DALAM_JAM_KERJA / NULLIF(TOTAL_KERJA, 0)) * 100) + 
        (0.3 * (TOTAL_MEMENUHI_SLA / NULLIF(TOTAL_KERJA, 0)) * 100)
    , 2), 0) AS SKOR_AKHIR,
    COALESCE(ROUND((TOTAL_LOLOS / NULLIF(TOTAL_KERJA, 0)) * 100, 2), 0) AS NILAI_PERFORMA,
    COALESCE(ROUND((TOTAL_DALAM_JAM_KERJA / NULLIF(TOTAL_KERJA, 0)) * 100, 2), 0) AS NILAI_PRODUKTIVITAS,
    COALESCE(ROUND((TOTAL_MEMENUHI_SLA / NULLIF(TOTAL_KERJA, 0)) * 100, 2), 0) AS NILAI_SLA,
    TOTAL_KERJA AS TOTAL_DOKUMEN_KERJA
FROM STATS_STAF
ORDER BY SKOR_AKHIR DESC"""

OSS_DETAIL_SQL = """SELECT 
    COALESCE(JENIS_IZIN, '-') AS JENIS_IZIN,
    COALESCE(SUB_JENIS_IZIN, '-') AS SUB_JENIS_IZIN,
    COALESCE(NO_PERMOHONAN, '-') AS NO_PERMOHONAN,
    COALESCE(PEMOHON, '-') AS NAMA_PEMOHON,
    COALESCE(KBLI, '-') AS KBLI,
    COALESCE(VERIFIKATOR, 'Sistem') AS VERIFIKATOR,
    COALESCE(STATUS_TERAKHIR, '-') AS STATUS_TERAKHIR,
    COALESCE(KATEGORI_STATUS, '-') AS KATEGORI_STATUS,
    TGL_MASUK AS TANGGAL_MASUK,
    TGL_STATUS_TERAKHIR AS TANGGAL_STATUS_TERAKHIR,
    COALESCE(BATAS_SLA_HARI, 0) AS BATAS_SLA_HARI,
    COALESCE(HARI_SLA_TERPAKAI, 0) AS SLA_TERPAKAI_HARI,
    COALESCE(HARI_TERLAMBAT, 0) AS KETERLAMBATAN_HARI,
    COALESCE(STATUS_PENCAPAIAN_SLA, '-') AS STATUS_SLA,
    COALESCE(SOURCE_TABLE, '-') AS SUMBER_TABEL
FROM US_DWH.BI_T_IZIN_OSS
WHERE 1=1
  AND {pilih_izin}
  AND {pilih_sub_izin}
  AND {filter_tahun}
  AND {filter_bulan}
  AND {rentang_tgl_masuk}
ORDER BY TGL_MASUK DESC"""

# ── iBOSS INTENTS ────────────────────────────────────────────────────────────

IBOSS_KPI_SQL = """SELECT 
    COUNT(TX_PERMOHONAN.SEQREQ) AS TOTAL_PERMOHONAN,
    COUNT(CASE WHEN TX_PERMOHONAN.STATUS_IZIN = '02030188' THEN 1 END) AS TOTAL_TERBIT,
    COUNT(CASE WHEN TX_PERMOHONAN.STATUS_IZIN = '02030199' THEN 1 END) AS TOTAL_TOLAK,
    COUNT(CASE WHEN TX_PERMOHONAN.STATUS_IZIN = '02030190' THEN 1 END) AS TOTAL_CABUT,
    COUNT(CASE WHEN TX_PERMOHONAN.STATUS_IZIN NOT IN ('02030188', '02030199', '02030190') THEN 1 END) AS TOTAL_PROSES
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}"""

IBOSS_OVERDUE_SQL = """SELECT 
    COUNT(TX_PERMOHONAN.SEQREQ) AS DOKUMEN_MELEWATI_SLA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND TX_PERMOHONAN.STATUS_IZIN NOT IN ('02030188', '02030199', '02030190')
  AND (
      SYSDATE - 
      CASE 
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
          ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
      END
  ) * 24 > 24
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}"""

IBOSS_GAUGE_SQL = """SELECT 
    SUM(CASE WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN 1 ELSE 0 END) 
    / NULLIF(COUNT(TX_PERMOHONAN.SEQREQ), 0) AS GAUGE_PERFORMA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}"""

IBOSS_SEBARAN_STATUS_SQL = """WITH BASE_DATA AS (
    SELECT 
        TX_PERMOHONAN.SEQREQ,
        TX_PERMOHONAN.STATUS_IZIN,
        CASE 
            WHEN LYN.IDLAYAN LIKE '018%' OR LYN.IDLAYAN IN ('012135') THEN 'Izin Usaha Kawasan'
            WHEN LYN.IDLAYAN LIKE '004%' OR LYN.IDLAYAN LIKE '005%' OR LYN.IDLAYAN LIKE '006%' OR LYN.IDLAYAN LIKE '007%' OR LYN.IDLAYAN LIKE '008%' OR LYN.IDLAYAN LIKE '009%' OR LYN.IDLAYAN LIKE '021%' THEN 'Izin Operasional Komersial'
            WHEN LYN.IDLAYAN IN ('012048', '009001', '01299', '011010', '012022') THEN 'Perizinan Pendukung'
            ELSE 'Lainnya'
        END AS KATEGORI_IZIN_BESAR,
        LYN.URAILAYAN AS SUB_JENIS_IZIN
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
),
DETEKSI_MODE AS (
    SELECT 
        SEQREQ, STATUS_IZIN, KATEGORI_IZIN_BESAR, SUB_JENIS_IZIN,
        MAX(CASE WHEN KATEGORI_IZIN_BESAR = 'Izin Usaha Kawasan' THEN 1 ELSE 0 END) OVER () AS HAS_IUK,
        MAX(CASE WHEN KATEGORI_IZIN_BESAR = 'Izin Operasional Komersial' THEN 1 ELSE 0 END) OVER () AS HAS_IOK,
        MAX(CASE WHEN KATEGORI_IZIN_BESAR = 'Perizinan Pendukung' THEN 1 ELSE 0 END) OVER () AS HAS_PP,
        MAX(CASE WHEN KATEGORI_IZIN_BESAR = 'Lainnya' THEN 1 ELSE 0 END) OVER () AS HAS_LAIN
    FROM BASE_DATA
)
SELECT 
    CASE 
        WHEN (HAS_IUK + HAS_IOK + HAS_PP + HAS_LAIN) = 1 THEN SUB_JENIS_IZIN
        ELSE KATEGORI_IZIN_BESAR
    END AS TAMPILAN_IZIN,
    COUNT(SEQREQ) AS TOTAL_PERMOHONAN,
    COUNT(CASE WHEN STATUS_IZIN = '02030188' THEN 1 END) AS TOTAL_TERBIT,
    COUNT(CASE WHEN STATUS_IZIN = '02030199' THEN 1 END) AS TOTAL_TOLAK,
    COUNT(CASE WHEN STATUS_IZIN = '02030190' THEN 1 END) AS TOTAL_CABUT,
    COUNT(CASE WHEN STATUS_IZIN NOT IN ('02030188', '02030199', '02030190') THEN 1 END) AS TOTAL_PROSES
FROM DETEKSI_MODE
GROUP BY 
    CASE 
        WHEN (HAS_IUK + HAS_IOK + HAS_PP + HAS_LAIN) = 1 THEN SUB_JENIS_IZIN
        ELSE KATEGORI_IZIN_BESAR
    END
ORDER BY TAMPILAN_IZIN ASC"""

IBOSS_SEBARAN_PROses_SQL = """WITH DATA_PROSES AS (
    SELECT 
        TX_PERMOHONAN.SEQREQ, 
        TX_PERMOHONAN.STATUS_IZIN, 
        R.KD_ROLE, 
        R.URAIAN_ROLE
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1
      AND TX_PERMOHONAN.STATUS_IZIN NOT IN ('02030188','02030199','02030190')
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
)
SELECT 
    'Dokumen Dalam Proses' AS SOURCE,
    CASE 
        WHEN STATUS_IZIN IN ('0203020102','0203020202') THEN 'Staf Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203020101','0203020201') THEN 'Kepala Seksi Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
        WHEN STATUS_IZIN = '02030100' THEN 'Direktur Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('02030101', '2100100') THEN 'Direktur PTSP'
        WHEN STATUS_IZIN = '02030301' OR UPPER(URAIAN_ROLE) LIKE '%PENERBITAN%' THEN 'Staf Penerbitan PTSP'
        ELSE 'Antrean Lain / Eksternal'
    END AS TARGET,
    COUNT(SEQREQ) AS VALUE
FROM DATA_PROSES
GROUP BY 
    CASE 
        WHEN STATUS_IZIN IN ('0203020102','0203020202') THEN 'Staf Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203020101','0203020201') THEN 'Kepala Seksi Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
        WHEN STATUS_IZIN = '02030100' THEN 'Direktur Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('02030101', '2100100') THEN 'Direktur PTSP'
        WHEN STATUS_IZIN = '02030301' OR UPPER(URAIAN_ROLE) LIKE '%PENERBITAN%' THEN 'Staf Penerbitan PTSP'
        ELSE 'Antrean Lain / Eksternal'
    END
UNION ALL
SELECT 
    CASE 
        WHEN STATUS_IZIN IN ('0203020102','0203020202') THEN 'Staf Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203020101','0203020201') THEN 'Kepala Seksi Lalu Lintas Barang'
    END AS SOURCE,
    CASE 
        WHEN STATUS_IZIN = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
        WHEN STATUS_IZIN = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
        WHEN STATUS_IZIN = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
        WHEN STATUS_IZIN = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
    END AS TARGET,
    COUNT(SEQREQ) AS VALUE
FROM DATA_PROSES
WHERE STATUS_IZIN IN ('0203020102','0203020202','0203020101','0203020201')
GROUP BY 
    CASE 
        WHEN STATUS_IZIN IN ('0203020102','0203020202') THEN 'Staf Lalu Lintas Barang'
        WHEN STATUS_IZIN IN ('0203020101','0203020201') THEN 'Kepala Seksi Lalu Lintas Barang'
    END,
    CASE 
        WHEN STATUS_IZIN = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
        WHEN STATUS_IZIN = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
        WHEN STATUS_IZIN = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
        WHEN STATUS_IZIN = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
    END"""

IBOSS_TREN_INFLOW_OUTFLOW_SQL = """WITH TREN_DATA AS (
    SELECT 
        TRUNC(TX_PERMOHONAN.TGL_DAFTAR) AS TANGGAL,
        1 AS MASUK, 
        0 AS TERBIT
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
    UNION ALL
    SELECT 
        TRUNC(TX_PERMOHONAN.LAST_PROSES) AS TANGGAL,
        0 AS MASUK, 
        1 AS TERBIT
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1 
      AND TX_PERMOHONAN.STATUS_IZIN = '02030188'
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
)
SELECT 
    TANGGAL,
    SUM(MASUK) AS INFLOW_MASUK,
    SUM(TERBIT) AS OUTFLOW_TERBIT
FROM TREN_DATA
WHERE TANGGAL IS NOT NULL
GROUP BY TANGGAL
ORDER BY TANGGAL ASC"""

IBOSS_FUNNEL_SQL = """WITH DOC_BASE AS (
    SELECT 
        TX_PERMOHONAN.SEQREQ, 
        TX_PERMOHONAN.STATUS_IZIN,
        CASE 
            WHEN 1=0 OR LOWER({pilih_seksi}) LIKE '%pemasukan%' THEN 'PEMASUKAN'
            WHEN 1=0 OR LOWER({pilih_seksi}) LIKE '%pengeluaran%' THEN 'PENGELUARAN'
            ELSE 'UMUM'
        END AS MODE_SEKSI
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
),
LOG_FLAGS AS (
    SELECT 
        L.ID_IZIN,
        MAX(CASE WHEN U.ROLE_ID = '0203020102' THEN 1 ELSE 0 END) AS STAF_MASUK,
        MAX(CASE WHEN U.ROLE_ID = '0203020202' THEN 1 ELSE 0 END) AS STAF_KELUAR,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020102', '0203020202', '02030301') OR UPPER(TR.URAIAN_ROLE) LIKE '%STAF%' OR UPPER(TR.URAIAN_ROLE) LIKE '%VERIFIKATOR%' THEN 1 ELSE 0 END) AS STAF_ANY,
        MAX(CASE WHEN U.ROLE_ID = '0203020101' THEN 1 ELSE 0 END) AS KASI_MASUK,
        MAX(CASE WHEN U.ROLE_ID = '0203020201' THEN 1 ELSE 0 END) AS KASI_KELUAR,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020101', '0203020201') OR UPPER(TR.URAIAN_ROLE) LIKE '%KASI%' OR UPPER(TR.URAIAN_ROLE) LIKE '%KEPALA SEKSI%' THEN 1 ELSE 0 END) AS KASI_ANY,
        MAX(CASE WHEN U.ROLE_ID IN ('0203011203','0203010203','0203020001') THEN 1 ELSE 0 END) AS FLAG_KASUBDIT,
        MAX(CASE WHEN U.ROLE_ID = '02030100' THEN 1 ELSE 0 END) AS FLAG_DIR_LALIN,
        MAX(CASE WHEN U.ROLE_ID IN ('02030101', '2100100') THEN 1 ELSE 0 END) AS FLAG_DIR_PTSP
    FROM US_OSS.T_LOG_LICENSING L
    JOIN US_OSS.TX_USERS U ON L.USER_ID = U.USER_ID
    LEFT JOIN US_OSS.TM_ROLE TR ON U.ROLE_ID = TR.KD_ROLE
    JOIN DOC_BASE B ON L.ID_IZIN = TO_CHAR(B.SEQREQ)
    GROUP BY L.ID_IZIN
),
MASTER_DATA AS (
    SELECT B.SEQREQ, B.STATUS_IZIN, B.MODE_SEKSI, L.*
    FROM DOC_BASE B
    LEFT JOIN LOG_FLAGS L ON TO_CHAR(B.SEQREQ) = L.ID_IZIN
    WHERE (B.MODE_SEKSI = 'UMUM') 
       OR (B.MODE_SEKSI = 'PEMASUKAN' AND L.STAF_MASUK = 1) 
       OR (B.MODE_SEKSI = 'PENGELUARAN' AND L.STAF_KELUAR = 1)
),
RESULTS AS (
    SELECT '1. Dokumen Masuk' AS TAHAPAN_PROSES, 1 AS URUTAN, COUNT(SEQREQ) AS JUMLAH_DOKUMEN FROM MASTER_DATA
    UNION ALL
    SELECT CASE WHEN MAX(MODE_SEKSI) = 'PEMASUKAN' THEN '2. Staf Seksi Pemasukan Barang' WHEN MAX(MODE_SEKSI) = 'PENGELUARAN' THEN '2. Staf Seksi Pengeluaran Barang' ELSE '2. Staf / Verifikator' END, 2, SUM(STAF_ANY) FROM MASTER_DATA
    UNION ALL
    SELECT CASE WHEN MAX(MODE_SEKSI) = 'PEMASUKAN' THEN '3. Kepala Seksi Pemasukan Barang' WHEN MAX(MODE_SEKSI) = 'PENGELUARAN' THEN '3. Kepala Seksi Pengeluaran Barang' ELSE '3. Kepala Seksi' END, 3, SUM(KASI_ANY) FROM MASTER_DATA
    UNION ALL
    SELECT '4. Kasubdit Perizinan', 4, SUM(FLAG_KASUBDIT) FROM MASTER_DATA
    UNION ALL
    SELECT '5. Direktur Lalu Lintas Barang', 5, SUM(FLAG_DIR_LALIN) FROM MASTER_DATA
    UNION ALL
    SELECT '6. Direktur PTSP', 6, SUM(FLAG_DIR_PTSP) FROM MASTER_DATA
    UNION ALL
    SELECT '7. Izin Terbit', 7, SUM(CASE WHEN STATUS_IZIN = '02030188' THEN 1 ELSE 0 END) FROM MASTER_DATA
)
SELECT TAHAPAN_PROSES, JUMLAH_DOKUMEN 
FROM RESULTS 
ORDER BY URUTAN ASC"""

IBOSS_RATA_WAKTU_SQL = """WITH RAW_DATA AS (
    SELECT 
        CASE 
            WHEN U.ROLE_ID = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
            WHEN U.ROLE_ID = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
            WHEN U.ROLE_ID = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
            WHEN U.ROLE_ID = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
            WHEN U.ROLE_ID IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
            WHEN U.ROLE_ID = '02030100' THEN 'Direktur Lalu Lintas Barang'
            WHEN U.ROLE_ID IN ('02030101', '2100100') THEN 'Direktur PTSP'
            WHEN U.ROLE_ID = '02030301' OR UPPER(R.URAIAN_ROLE) LIKE '%PENERBITAN%' THEN 'Staf Penerbitan PTSP'
        END AS JABATAN,
        T_LOG_LICENSING.DIFFERENCE_TIME
    FROM US_OSS.T_LOG_LICENSING
    JOIN US_OSS.TX_USERS U ON T_LOG_LICENSING.USER_ID = U.USER_ID
    JOIN US_OSS.TM_ROLE R ON U.ROLE_ID = R.KD_ROLE
    JOIN US_OSS.TX_PERMOHONAN ON T_LOG_LICENSING.ID_IZIN = TO_CHAR(TX_PERMOHONAN.SEQREQ)
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    WHERE T_LOG_LICENSING.USER_ID != 0 
      AND T_LOG_LICENSING.DIFFERENCE_TIME IS NOT NULL
      AND (U.ROLE_ID IN ('0203020102','0203020202','0203020101','0203020201','0203011203','0203010203','0203020001','02030100','02030101','2100100','02030301') OR UPPER(R.URAIAN_ROLE) LIKE '%PENERBITAN%')
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_izin_iboss}
)
SELECT 
    JABATAN,
    ROUND(AVG(DIFFERENCE_TIME) / 60, 2) AS RATA_WAKTU_MENIT
FROM RAW_DATA
WHERE JABATAN IS NOT NULL
GROUP BY JABATAN
ORDER BY AVG(DIFFERENCE_TIME) DESC"""

IBOSS_KEPATUHAN_SLA_SQL = """SELECT 
    SUM(
        CASE 
            WHEN (
                CASE 
                    WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN CAST(TX_PERMOHONAN.LAST_PROSES AS DATE)
                    ELSE SYSDATE
                END
                - 
                CASE 
                    WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
                         THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
                    WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
                         THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
                    ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
                END
            ) * 24 <= 24 THEN 1 
            ELSE 0 
        END
    ) / NULLIF(COUNT(TX_PERMOHONAN.SEQREQ), 0) AS GAUGE_KEPATUHAN_SLA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}"""

IBOSS_LEADERBOARD_SLA_SQL = """WITH RAW_DATA AS (
    SELECT 
        CASE 
            WHEN TX_PERMOHONAN.STATUS_IZIN IN ('00000000', '02030301') THEN 'Staf Penerbitan PTSP'
            WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
            WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
            WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
            WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
            WHEN TX_PERMOHONAN.STATUS_IZIN IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
            WHEN TX_PERMOHONAN.STATUS_IZIN = '02030100' THEN 'Direktur Lalu Lintas Barang'
            WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030101', '2100100') THEN 'Direktur PTSP'
            WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN 'Selesai (Terbit/Tolak/Cabut)'
            ELSE NVL(R.URAIAN_ROLE, 'Lainnya (Kode: ' || TX_PERMOHONAN.STATUS_IZIN || ')')
        END AS POSISI_DOKUMEN,
        (CASE 
            WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN CAST(TX_PERMOHONAN.LAST_PROSES AS DATE)
            ELSE SYSDATE
        END)
        - 
        (CASE 
            WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
                 THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
            WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
                 THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
            ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
        END) AS UMUR_DOKUMEN
    FROM US_OSS.TX_PERMOHONAN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE TX_PERMOHONAN.STATUSINVOICE = 1 
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
)
SELECT 
    NVL(POSISI_DOKUMEN, 'TOTAL KESELURUHAN') AS POSISI_DOKUMEN,
    COUNT(*) AS TOTAL_DOKUMEN,
    SUM(CASE WHEN UMUR_DOKUMEN * 24 <= 24 THEN 1 ELSE 0 END) AS DOK_MEMENUHI_SLA,
    SUM(CASE WHEN UMUR_DOKUMEN * 24 > 24 THEN 1 ELSE 0 END) AS DOK_MELEWATI_SLA
FROM RAW_DATA
GROUP BY ROLLUP(POSISI_DOKUMEN)
ORDER BY 
    CASE WHEN POSISI_DOKUMEN IS NULL THEN 1 ELSE 0 END ASC,
    DOK_MELEWATI_SLA DESC, 
    TOTAL_DOKUMEN DESC"""

IBOSS_SEBARAN_OVERDUE_SQL = """SELECT 
    CASE 
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '02030100' THEN 'Direktur Lalu Lintas Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030101', '2100100') THEN 'Direktur PTSP'
        ELSE 'Staf Penerbitan'
    END AS POSISI_DOKUMEN,
    COUNT(TX_PERMOHONAN.SEQREQ) AS DOKUMEN_MELEWATI_SLA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1 
  AND (
      CASE 
          WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN CAST(TX_PERMOHONAN.LAST_PROSES AS DATE)
          ELSE SYSDATE
      END
      - 
      CASE 
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
          ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
      END
  ) * 24 > 24
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}
GROUP BY 
    CASE 
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020102' THEN 'Staf Seksi Pemasukan Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020202' THEN 'Staf Seksi Pengeluaran Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020101' THEN 'Kepala Seksi Pemasukan Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '0203020201' THEN 'Kepala Seksi Pengeluaran Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN IN ('0203011203','0203010203','0203020001') THEN 'Kepala Subdit Perizinan'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '02030100' THEN 'Direktur Lalu Lintas Barang'
        WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030101', '2100100') THEN 'Direktur PTSP'
        ELSE 'Staf Penerbitan'
    END
ORDER BY POSISI_DOKUMEN ASC"""

IBOSS_TOTAL_OVERDUE_SQL = """SELECT 
    COUNT(TX_PERMOHONAN.SEQREQ) AS TOTAL_MELEWATI_SLA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1 
  AND (
      CASE 
          WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN CAST(TX_PERMOHONAN.LAST_PROSES AS DATE)
          ELSE SYSDATE
      END
      - 
      CASE 
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
          WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
               THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
          ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
      END
  ) * 24 > 24
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}"""

IBOSS_PROPORSI_KERJA_SQL = """SELECT 
    CASE 
        WHEN TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT', 'SUN') 
        AND TO_NUMBER(TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'HH24MI')) BETWEEN 800 AND 1630 
        THEN 'Jam Kerja' 
        ELSE 'Di luar jam kerja' 
    END AS KATEGORI_WAKTU,
    COUNT(TX_PERMOHONAN.SEQREQ) AS JUMLAH_DOKUMEN
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}
GROUP BY 
    CASE 
        WHEN TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT', 'SUN') 
        AND TO_NUMBER(TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'HH24MI')) BETWEEN 800 AND 1630 
        THEN 'Jam Kerja' 
        ELSE 'Di luar jam kerja' 
    END"""

IBOSS_RAPOR_STAF_SQL = """WITH DOC_SLA AS (
    SELECT ID_IZIN, SUM(DIFFERENCE_TIME) AS TOTAL_WAKTU_DETIK
    FROM US_OSS.T_LOG_LICENSING
    WHERE DIFFERENCE_TIME IS NOT NULL
    GROUP BY ID_IZIN
),
STAFF_LOGS AS (
    SELECT 
        U.NAME,
        L.LOG_ID,
        TX_PERMOHONAN.STATUS_IZIN,
        CASE 
            WHEN TO_CHAR(L.ACTION_TIME, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT', 'SUN') 
            AND TO_NUMBER(TO_CHAR(L.ACTION_TIME, 'HH24MI')) BETWEEN 800 AND 1630 
            THEN 1 ELSE 0 
        END AS IS_JAM_KERJA,
        CASE 
            WHEN (
                CAST(NVL(TX_PERMOHONAN.LAST_PROSES, SYSDATE) AS DATE)
                -
                (CASE 
                    WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
                         THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
                    WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
                         THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
                    ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
                END)
            ) * 24 <= 24 THEN 1 
            WHEN D.TOTAL_WAKTU_DETIK <= 86400 THEN 1 
            ELSE 0 
        END AS IS_MEMENUHI_SLA
    FROM US_OSS.T_LOG_LICENSING L
    JOIN US_OSS.TX_USERS U ON L.USER_ID = U.USER_ID
    JOIN US_OSS.TX_PERMOHONAN ON L.ID_IZIN = TO_CHAR(TX_PERMOHONAN.SEQREQ)
    LEFT JOIN DOC_SLA D ON L.ID_IZIN = D.ID_IZIN
    LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
    LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
    WHERE L.USER_ID != 0 AND L.DIFFERENCE_TIME IS NOT NULL
      AND U.ROLE_ID IN ('0203020102','0203020202')
      AND TX_PERMOHONAN.STATUSINVOICE = 1
      AND {rentang_waktu}
      AND {pilih_tahun}
      AND {pilih_bulan}
      AND {pilih_role}
      AND {pilih_izin_iboss}
),
STAFF_AGGR AS (
    SELECT 
        NAME,
        COUNT(LOG_ID) AS TOTAL_KERJA,
        SUM(CASE WHEN STATUS_IZIN NOT IN ('0203020102','0203020202') THEN 1 ELSE 0 END) AS TOTAL_LOLOS,
        SUM(IS_JAM_KERJA) AS TOTAL_DALAM_JAM_KERJA,
        SUM(IS_MEMENUHI_SLA) AS TOTAL_MEMENUHI_SLA
    FROM STAFF_LOGS
    GROUP BY NAME
)
SELECT 
    NAME AS NAMA_STAF,
    ROUND(
        (0.4 * (TOTAL_LOLOS / NULLIF(TOTAL_KERJA, 0)) * 100) + 
        (0.3 * (TOTAL_DALAM_JAM_KERJA / NULLIF(TOTAL_KERJA, 0)) * 100) + 
        (0.3 * (TOTAL_MEMENUHI_SLA / NULLIF(TOTAL_KERJA, 0)) * 100)
    , 2) AS SKOR_AKHIR,
    ROUND((TOTAL_LOLOS / NULLIF(TOTAL_KERJA, 0)) * 100, 2) AS NILAI_PERFORMA,
    ROUND((TOTAL_DALAM_JAM_KERJA / NULLIF(TOTAL_KERJA, 0)) * 100, 2) AS NILAI_PRODUKTIVITAS,
    ROUND((TOTAL_MEMENUHI_SLA / NULLIF(TOTAL_KERJA, 0)) * 100, 2) AS NILAI_SLA
FROM STAFF_AGGR
ORDER BY SKOR_AKHIR DESC"""

IBOSS_DETAIL_SQL = """WITH DOC_LOGS AS (
    SELECT 
        L.ID_IZIN,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020102','0203020202') THEN L.ACTION_TIME END) AS TGL_STAFF,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020102','0203020202') THEN U.NAME END) AS USER_STAFF,
        SUM(CASE WHEN U.ROLE_ID IN ('0203020102','0203020202') THEN L.DIFFERENCE_TIME ELSE 0 END) AS WAKTU_STAFF_DETIK,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020101','0203020201') THEN L.ACTION_TIME END) AS TGL_VER_1,
        MAX(CASE WHEN U.ROLE_ID IN ('0203020101','0203020201') THEN U.NAME END) AS USER_VER_1,
        SUM(CASE WHEN U.ROLE_ID IN ('0203020101','0203020201') THEN L.DIFFERENCE_TIME ELSE 0 END) AS WAKTU_VER_1_DETIK,
        MAX(CASE WHEN U.ROLE_ID IN ('0203011203','0203010203','0203020001') THEN L.ACTION_TIME END) AS TGL_VER_2,
        MAX(CASE WHEN U.ROLE_ID IN ('0203011203','0203010203','0203020001') THEN U.NAME END) AS USER_VER_2,
        SUM(CASE WHEN U.ROLE_ID IN ('0203011203','0203010203','0203020001') THEN L.DIFFERENCE_TIME ELSE 0 END) AS WAKTU_VER_2_DETIK,
        MAX(CASE WHEN U.ROLE_ID = '02030100' THEN L.ACTION_TIME END) AS TGL_DIRLALIN,
        MAX(CASE WHEN U.ROLE_ID = '02030100' THEN U.NAME END) AS USER_DIRLALIN,
        SUM(CASE WHEN U.ROLE_ID = '02030100' THEN L.DIFFERENCE_TIME ELSE 0 END) AS WAKTU_DIRLALIN_DETIK,
        MAX(CASE WHEN U.ROLE_ID IN ('02030101', '2100100') THEN L.ACTION_TIME END) AS TGL_PTSP,
        MAX(CASE WHEN U.ROLE_ID IN ('02030101', '2100100') THEN U.NAME END) AS USER_PTSP,
        SUM(CASE WHEN U.ROLE_ID IN ('02030101', '2100100') THEN L.DIFFERENCE_TIME ELSE 0 END) AS WAKTU_PTSP_DETIK,
        SUM(L.DIFFERENCE_TIME) AS TOTAL_WAKTU_DETIK
    FROM US_OSS.T_LOG_LICENSING L
    JOIN US_OSS.TX_USERS U ON L.USER_ID = U.USER_ID
    WHERE L.USER_ID != 0 AND L.DIFFERENCE_TIME IS NOT NULL
    GROUP BY L.ID_IZIN
)
SELECT 
    TX_PERMOHONAN.SEQREQ AS NO_DAFTAR,
    COALESCE(LYN.URAILAYAN, TX_PERMOHONAN.URAILAYAN) AS NAMA_LAYANAN,
    TX_PERMOHONAN.NAMA_PERSH AS NAMA_PERUSAHAAN,
    TX_PERMOHONAN.NO_IJIN AS NO_IZIN,
    CASE 
        WHEN TX_PERMOHONAN.STATUS_IZIN = '02030188' THEN 'Terbit'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '02030199' THEN 'Ditolak'
        WHEN TX_PERMOHONAN.STATUS_IZIN = '02030190' THEN 'Dicabut'
        ELSE 'Dalam Proses'
    END AS STATUS_IZIN,
    TX_PERMOHONAN.TGL_DAFTAR AS TGL_MOHON,
    TX_PERMOHONAN.TGLBAYAR AS TGL_BAYAR,
    CASE 
        WHEN TO_CHAR(TX_PERMOHONAN.TGLBAYAR, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT', 'SUN') 
        AND TO_NUMBER(TO_CHAR(TX_PERMOHONAN.TGLBAYAR, 'HH24MI')) BETWEEN 800 AND 1630 
        THEN 'Dalam Jam Kerja' 
        ELSE 'Di Luar Jam Kerja' 
    END AS STATUS_WAKTU_BAYAR,
    DL.TGL_STAFF AS TGL_PROSES_STAF,
    DL.USER_STAFF AS USER_PEMROSES_STAF,
    ROUND(DL.WAKTU_STAFF_DETIK / 3600, 2) AS NILAI_STAFF_JAM,
    DL.TGL_VER_1 AS TGL_VER_I,
    DL.USER_VER_1 AS USER_VER_I,
    ROUND(DL.WAKTU_VER_1_DETIK / 3600, 2) AS NILAI_VER_1_JAM,
    DL.TGL_VER_2 AS TGL_VER_II,
    DL.USER_VER_2 AS USER_VER_II,
    ROUND(DL.WAKTU_VER_2_DETIK / 3600, 2) AS NILAI_VER_2_JAM,
    DL.TGL_DIRLALIN AS TGL_VALIDASI_DIRLALIN,
    DL.USER_DIRLALIN AS USER_DIRLALIN,
    ROUND(DL.WAKTU_DIRLALIN_DETIK / 3600, 2) AS NILAI_DIRLALIN_JAM,
    DL.TGL_PTSP AS TGL_APPROVE_PTSP,
    DL.USER_PTSP AS USER_PTSP,
    ROUND(DL.WAKTU_PTSP_DETIK / 3600, 2) AS NILAI_PTSP_JAM,
    CASE 
        WHEN (
            CASE 
                WHEN TX_PERMOHONAN.STATUS_IZIN IN ('02030188', '02030199', '02030190') THEN CAST(TX_PERMOHONAN.LAST_PROSES AS DATE)
                ELSE SYSDATE
            END
            -
            CASE 
                WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) > (16.5 / 24) 
                     THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + 1 + (8 / 24)
                WHEN (CAST(TX_PERMOHONAN.TGLBAYAR AS DATE) - TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE))) < (8 / 24) 
                     THEN TRUNC(CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)) + (8 / 24)
                ELSE CAST(TX_PERMOHONAN.TGLBAYAR AS DATE)
            END
        ) * 24 <= 24 THEN 'Memenuhi SLA'
        ELSE 'Melewati SLA'
    END AS STATUS_KEPATUHAN_SLA
FROM US_OSS.TX_PERMOHONAN
LEFT JOIN US_OSS.TM_LAYAN LYN ON TX_PERMOHONAN.IDLAYAN = LYN.IDLAYAN
LEFT JOIN US_OSS.TM_ROLE R ON TX_PERMOHONAN.STATUS_IZIN = R.KD_ROLE
LEFT JOIN DOC_LOGS DL ON TO_CHAR(TX_PERMOHONAN.SEQREQ) = DL.ID_IZIN
WHERE TX_PERMOHONAN.STATUSINVOICE = 1
  AND {rentang_waktu}
  AND {pilih_tahun}
  AND {pilih_bulan}
  AND {pilih_role}
  AND {pilih_izin_iboss}
ORDER BY TX_PERMOHONAN.TGL_DAFTAR DESC"""

# ── BUILD ALL INTENTS ────────────────────────────────────────────────────────

OSS_INTENTS = [
    {
        "id": "oss_kpi_card",
        "description": "OSS: KPI Card — ringkasan seluruh permohonan (total, terbit, tolak, proses pelaku usaha, dalam proses, overdue)",
        "sql_template": OSS_KPI_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Ringkasan KPI OSS", "Total permohonan izin OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["kpi.*oss", "oss.*kpi", "ringkasan.*oss", "total.*oss"],
        "llm_label": "Ringkasan KPI seluruh permohonan OSS",
        "insight_template": {
            "judul": "Ringkasan KPI Seluruh Permohonan OSS",
            "insight": "Distribusi [TOTAL_DOKUMEN] permohonan OSS menunjukkan komposisi [TOTAL_TERBIT] terbit, [TOTAL_TOLAK] ditolak, [TOTAL_DALAM_PROSES] dalam proses, dan [TOTAL_MELEWATI_SLA] melewati SLA.",
            "rekomendasi": "Gunakan panel ini untuk memonitor kesehatan pipeline perizinan OSS secara real-time.",
        },
        "intent_rules": {
            "insight_patterns": ["Total {total_dokumen} dokumen OSS dengan {total_terbit} terbit."],
            "bullet_patterns": ["Terbit: {total_terbit}", "Dalam Proses: {total_dalam_proses}", "Overdue: {total_melewati_sla}"],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "oss_gauge_performa",
        "description": "OSS: Gauge performa penyelesaian permohonan",
        "sql_template": OSS_GAUGE_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Performa penyelesaian OSS", "Gauge OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["gauge.*oss", "performa.*oss", "oss.*performa"],
        "llm_label": "Gauge performa penyelesaian OSS",
        "insight_template": {
            "judul": "Gauge Performa Penyelesaian OSS",
            "insight": "Capaian [PERFORMA_PENYELESAIAN] pada Gauge Chart mencerminkan persentase penyelesaian permohonan OSS yang sudah tuntas.",
            "rekomendasi": "Analisis lebih lanjut per jenis izin untuk identifikasi sektor yang perlu perbaikan.",
        },
        "intent_rules": {
            "insight_patterns": ["Performa OSS: {performa_penyelesaian}."],
            "bullet_patterns": ["Skor performa: {performa_penyelesaian}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Performa Penyelesaian OSS", "value_column": "PERFORMA_PENYELESAIAN"},
    },
    {
        "id": "oss_sebaran_jenis_perizinan",
        "description": "OSS: Sebaran jenis perizinan (stacked bar per jenis izin vs status)",
        "sql_template": OSS_SEBARAN_JENIS_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Sebaran jenis perizinan OSS", "Distribusi per jenis izin OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["sebaran.*jenis.*oss", "distribusi.*izin.*oss", "perizinan.*oss"],
        "llm_label": "Sebaran jenis perizinan OSS per status",
        "insight_template": {
            "judul": "Sebaran Jenis Perizinan OSS",
            "insight": "Distribusi [TOTAL] dokumen per jenis izin menunjukkan komposisi dan status masing-masing kelompok perizinan.",
            "rekomendasi": "Filter per jenis izin untuk melihat detail sebaran status yang lebih spesifik.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} kelompok jenis izin OSS."],
            "bullet_patterns": ["Jenis terbanyak: {top_entity} = {top_value} dokumen."],
            "facts_to_use": ["ranking", "filters", "row_count"],
        },
        "format_config": {"type": "table", "title": "Sebaran Jenis Perizinan OSS", "columns": ["SUMBU_X", "LABEL_STACK_STATUS", "JUMLAH_DOKUMEN"]},
    },
    {
        "id": "oss_sebaran_risiko",
        "description": "OSS: Sebaran tingkat risiko permohonan",
        "sql_template": OSS_SEBARAN_RISIKO_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Sebaran risiko OSS", "Tingkat risiko permohonan OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["risiko.*oss", "sebaran.*risiko", "tingkat.*risiko.*oss"],
        "llm_label": "Sebaran tingkat risiko permohonan OSS",
        "insight_template": {
            "judul": "Sebaran Tingkat Risiko OSS",
            "insight": "Dari [TOTAL] dokumen, sebaran tingkat risiko menunjukkan proporsi risiko rendah, menengah, dan tinggi.",
            "rekomendasi": "Perhatikan proporsi risiko tinggi untuk dilakukan penanganan prioritas.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} tingkat risiko terdeteksi."],
            "bullet_patterns": ["Risiko tertinggi: {top_entity} = {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count"],
        },
        "format_config": {"type": "table", "title": "Sebaran Risiko OSS", "columns": ["TINGKAT_RISIKO", "JUMLAH_DOKUMEN"]},
    },
    {
        "id": "oss_sebaran_status_permohonan",
        "description": "OSS: Sebaran status permohonan (alur/sankey dari total ke jenis izin ke status)",
        "sql_template": OSS_SEBARAN_STATUS_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Flow status OSS", "Alur permohonan OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["flow.*oss", "sankey.*oss", "alur.*oss", "status.*oss"],
        "llm_label": "Diagram alur/Sankey status permohonan OSS",
        "insight_template": {
            "judul": "Diagram Alur Status Permohonan OSS",
            "insight": "Aliran [TOTAL] dokumen dari jenis izin ke status menunjukkan distribusi proses.",
            "rekomendasi": "Filter jenis izin untuk fokus pada satu kategori tertentu.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} aliran data pada diagram Sankey OSS."],
            "bullet_patterns": ["Total aliran: {row_count} baris."],
            "facts_to_use": ["filters", "row_count"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "oss_tren_inflow_outflow",
        "description": "OSS: Tren inflow (permohonan masuk) vs outflow (terbit)",
        "sql_template": OSS_TREN_INFLOW_OUTFLOW_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Tren inflow outflow OSS", "Perbandingan masuk terbit OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["tren.*oss", "inflow.*oss", "outflow.*oss", "masuk.*terbit.*oss"],
        "llm_label": "Tren inflow vs outflow OSS",
        "insight_template": {
            "judul": "Tren Inflow vs Outflow OSS",
            "insight": "Selama periode terpilih, inflow [TOTAL_INFLOW] dan outflow [TOTAL_OUTFLOW] menunjukkan gap yang perlu dimonitor.",
            "rekomendasi": "Sesuaikan kapasitas verifikasi dengan rata-rata inflow harian.",
        },
        "intent_rules": {
            "insight_patterns": ["Tren inflow vs outflow OSS pada {period_count} periode."],
            "bullet_patterns": ["Terakhir: inflow {inflow_value}, outflow {outflow_value}."],
            "facts_to_use": ["series", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "oss_funnel_kemacetan",
        "description": "OSS: Pemetaan titik kemacetan proses per tahapan",
        "sql_template": OSS_FUNNEL_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Funnel OSS", "Kemacetan proses OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["funnel.*oss", "kemacetan.*oss", "bottleneck.*oss", "macet.*oss"],
        "llm_label": "Pemetaan titik kemacetan proses OSS",
        "insight_template": {
            "judul": "Analisis Kemacetan Proses OSS",
            "insight": "Funnel ini memetakan transisi [TOTAL] dokumen antar tahapan, menunjukkan titik penyempitan.",
            "rekomendasi": "Intervensi pada bottleneck utama dengan penambahan sumber daya atau optimasi SOP.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} tahapan funnel OSS."],
            "bullet_patterns": ["Tahapan teratas: {top_entity} = {top_value} dokumen."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Pemetaan Kemacetan OSS", "columns": ["TAHAPAN", "JUMLAH"]},
    },
    {
        "id": "oss_kepatuhan_sla",
        "description": "OSS: Kepatuhan SLA permohonan izin",
        "sql_template": OSS_SLA_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["SLA OSS", "Kepatuhan SLA OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["sla.*oss", "kepatuhan.*oss", "oss.*sla"],
        "llm_label": "Kepatuhan SLA OSS",
        "insight_template": {
            "judul": "Kepatuhan SLA OSS",
            "insight": "Capaian [KEPATUHAN_SLA] menggambarkan tingkat kepatuhan layanan terhadap SLA.",
            "rekomendasi": "Identifikasi permohonan yang melanggar SLA untuk tindak lanjut prioritas.",
        },
        "intent_rules": {
            "insight_patterns": ["Kepatuhan SLA OSS: {kepatuhan_sla}."],
            "bullet_patterns": ["Skor SLA: {kepatuhan_sla}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Kepatuhan SLA OSS", "value_column": "KEPATUHAN_SLA"},
    },
    {
        "id": "oss_leaderboard_sla",
        "description": "OSS: Leaderboard kepatuhan SLA per verifikator",
        "sql_template": OSS_LEADERBOARD_SLA_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Leaderboard SLA OSS", "Ranking kepatuhan SLA OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["leaderboard.*oss", "ranking.*sla.*oss", "sla.*verifikator.*oss"],
        "llm_label": "Leaderboard kepatuhan SLA per verifikator OSS",
        "insight_template": {
            "judul": "Leaderboard Kepatuhan SLA OSS",
            "insight": "Perbandingan kepatuhan SLA antar verifikator menunjukkan variasi kinerja.",
            "rekomendasi": "Berikan pelatihan pada verifikator dengan tingkat pelanggaran SLA tertinggi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} entri dalam leaderboard SLA OSS."],
            "bullet_patterns": ["Verifikator dengan pelanggaran terbanyak: {top_entity}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Leaderboard SLA OSS", "columns": ["NAMA", "JABATAN", "TOTAL_DOKUMEN", "JUMLAH_SESUAI_SLA", "JUMLAH_LEWAT_SLA"]},
    },
    {
        "id": "oss_rapor_staf",
        "description": "OSS: Rapor kinerja verifikator (skor akhir, performa, produktivitas, SLA)",
        "sql_template": OSS_RAPOR_STAF_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Rapor staf OSS", "Kinerja verifikator OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["rapor.*oss", "staf.*oss", "verifikator.*oss", "kinerja.*oss"],
        "llm_label": "Rapor kinerja verifikator OSS",
        "insight_template": {
            "judul": "Rapor Kinerja Verifikator OSS",
            "insight": "Skor akhir verifikator berkisar antara [SKOR_MIN] hingga [SKOR_MAX] dengan rata-rata [SKOR_RATA].",
            "rekomendasi": "Gunakan data ini untuk program best practice sharing dan pelatihan terarah.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} staf OSS dievaluasi."],
            "bullet_patterns": ["Staf terbaik: {top_entity} skor {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Rapor Staf OSS", "columns": ["NAMA_STAF", "SKOR_AKHIR", "NILAI_PERFORMA", "NILAI_PRODUKTIVITAS", "NILAI_SLA", "TOTAL_DOKUMEN_KERJA"]},
    },
    {
        "id": "oss_detail_permohonan",
        "description": "OSS: Detail permohonan (tabel lengkap semua kolom)",
        "sql_template": OSS_DETAIL_SQL,
        "params": {
            "pilih_izin": "Filter jenis izin (contoh: UPPER(JENIS_IZIN) = UPPER('PB'))",
            "pilih_sub_izin": "Filter sub jenis izin (contoh: UPPER(SUB_JENIS_IZIN) = UPPER('PB UMKU'))",
            "filter_tahun": "Filter tahun (contoh: TAHUN = '2025')",
            "filter_bulan": "Filter bulan (contoh: BULAN = '01')",
            "rentang_tgl_masuk": "Filter rentang tanggal masuk (contoh: TGL_MASUK >= TO_DATE('2025-01-01','YYYY-MM-DD'))",
        },
        "examples": ["Detail permohonan OSS", "Data lengkap OSS"],
        "active": True,
        "source": "oss",
        "keyword_patterns": ["detail.*oss", "data.*oss", "tabel.*oss", "permohonan.*oss"],
        "llm_label": "Detail permohonan OSS",
        "insight_template": {
            "judul": "Detail Permohonan OSS",
            "insight": "Menampilkan [row_count] baris data permohonan OSS.",
            "rekomendasi": "Gunakan filter untuk mempersempit pencarian berdasarkan jenis izin atau periode.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} baris detail permohonan OSS."],
            "bullet_patterns": ["Total baris: {row_count}."],
            "facts_to_use": ["filters", "row_count"],
        },
        "format_config": {"type": "table", "title": "Detail Permohonan OSS", "columns": ["NO_PERMOHONAN", "JENIS_IZIN", "SUB_JENIS_IZIN", "NAMA_PEMOHON", "KATEGORI_STATUS", "STATUS_SLA"]},
    },
]

IBOSS_INTENTS = [
    {
        "id": "iboss_kpi_card",
        "description": "iBOSS: KPI Card — ringkasan seluruh permohonan (total, terbit, tolak, cabut, proses)",
        "sql_template": IBOSS_KPI_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu (contoh: TX_PERMOHONAN.TGL_DAFTAR >= TO_DATE('2025-01-01','YYYY-MM-DD') AND TX_PERMOHONAN.TGL_DAFTAR <= TO_DATE('2025-12-31','YYYY-MM-DD'))",
            "pilih_tahun": "Filter tahun (contoh: TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'YYYY') = '2025')",
            "pilih_bulan": "Filter bulan (contoh: TO_CHAR(TX_PERMOHONAN.TGL_DAFTAR, 'FMMM') = '01')",
            "pilih_role": "Filter role/status izin (contoh: R.KD_ROLE = '02030188' OR R.URAIAN_ROLE = 'TERBIT')",
            "pilih_izin_iboss": "Filter kategori izin iBOSS (contoh: 'Izin Usaha Kawasan')",
        },
        "examples": ["Ringkasan KPI iBOSS", "Total permohonan iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["kpi.*iboss", "iboss.*kpi", "ringkasan.*iboss", "total.*iboss"],
        "llm_label": "Ringkasan KPI seluruh permohonan iBOSS",
        "insight_template": {
            "judul": "Ringkasan KPI Seluruh Permohonan iBOSS",
            "insight": "Distribusi [TOTAL_PERMOHONAN] permohonan iBOSS menunjukkan [TOTAL_TERBIT] terbit, [TOTAL_TOLAK] ditolak, [TOTAL_CABUT] dicabut, dan [TOTAL_PROSES] dalam proses.",
            "rekomendasi": "Gunakan panel ini untuk monitoring pipeline perizinan iBOSS secara real-time.",
        },
        "intent_rules": {
            "insight_patterns": ["Total {total_permohonan} dokumen iBOSS."],
            "bullet_patterns": ["Terbit: {total_terbit}", "Proses: {total_proses}"],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "iboss_overdue",
        "description": "iBOSS: Total dokumen melewati SLA (overdue real-time)",
        "sql_template": IBOSS_OVERDUE_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Overdue iBOSS", "Dokumen lewat SLA iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["overdue.*iboss", "sla.*iboss", "lewat.*iboss"],
        "llm_label": "Total dokumen melewati SLA iBOSS",
        "insight_template": {
            "judul": "Total Overdue iBOSS",
            "insight": "Terdapat [DOKUMEN_MELEWATI_SLA] dokumen yang melewati batas SLA.",
            "rekomendasi": "Segera identifikasi dan tindak lanjuti dokumen yang melewati SLA.",
        },
        "intent_rules": {
            "insight_patterns": ["{dokumen_melewati_sla} dokumen overdue iBOSS."],
            "bullet_patterns": ["Overdue: {dokumen_melewati_sla}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Overdue iBOSS", "value_column": "DOKUMEN_MELEWATI_SLA"},
    },
    {
        "id": "iboss_gauge_performa",
        "description": "iBOSS: Gauge performa penyelesaian permohonan",
        "sql_template": IBOSS_GAUGE_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Performa iBOSS", "Gauge iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["gauge.*iboss", "performa.*iboss", "iboss.*performa"],
        "llm_label": "Gauge performa penyelesaian iBOSS",
        "insight_template": {
            "judul": "Gauge Performa iBOSS",
            "insight": "Capaian [GAUGE_PERFORMA] pada Gauge Chart menunjukkan persentase penyelesaian permohonan iBOSS.",
            "rekomendasi": "Analisis lebih lanjut per kategori izin untuk identifikasi area perbaikan.",
        },
        "intent_rules": {
            "insight_patterns": ["Performa iBOSS: {gauge_performa}."],
            "bullet_patterns": ["Skor performa: {gauge_performa}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Performa iBOSS", "value_column": "GAUGE_PERFORMA"},
    },
    {
        "id": "iboss_sebaran_status",
        "description": "iBOSS: Sebaran izin berdasarkan status (per kategori izin besar atau sub jenis)",
        "sql_template": IBOSS_SEBARAN_STATUS_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Sebaran status iBOSS", "Distribusi izin iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["sebaran.*iboss", "status.*iboss", "distribusi.*iboss"],
        "llm_label": "Sebaran izin iBOSS berdasarkan status",
        "insight_template": {
            "judul": "Sebaran Izin iBOSS per Status",
            "insight": "Distribusi [TOTAL] dokumen per kategori izin menunjukkan komposisi status masing-masing.",
            "rekomendasi": "Gunakan filter kategori izin untuk melihat detail sub-jenis izin.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} kelompok izin iBOSS."],
            "bullet_patterns": ["Kelompok terbanyak: {top_entity} = {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Sebaran Status iBOSS", "columns": ["TAMPILAN_IZIN", "TOTAL_PERMOHONAN", "TOTAL_TERBIT", "TOTAL_TOLAK", "TOTAL_CABUT", "TOTAL_PROSES"]},
    },
    {
        "id": "iboss_sebaran_proses",
        "description": "iBOSS: Sebaran perizinan dalam proses (flow/sankey per role)",
        "sql_template": IBOSS_SEBARAN_PROses_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Flow proses iBOSS", "Sebaran proses iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["flow.*iboss", "sankey.*iboss", "proses.*iboss"],
        "llm_label": "Sebaran perizinan dalam proses iBOSS",
        "insight_template": {
            "judul": "Sebaran Proses iBOSS",
            "insight": "Aliran dokumen dalam proses menunjukkan bottleneck potensial di setiap role.",
            "rekomendasi": "Perhatikan role dengan akumulasi dokumen terbanyak untuk optimalisasi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} aliran proses iBOSS."],
            "bullet_patterns": ["Total aliran: {row_count} baris."],
            "facts_to_use": ["filters", "row_count"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "iboss_tren_inflow_outflow",
        "description": "iBOSS: Tren inflow (masuk) vs outflow (terbit) per hari",
        "sql_template": IBOSS_TREN_INFLOW_OUTFLOW_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Tren inflow outflow iBOSS", "Perbandingan masuk terbit iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["tren.*iboss", "inflow.*iboss", "outflow.*iboss", "masuk.*terbit.*iboss"],
        "llm_label": "Tren inflow vs outflow iBOSS",
        "insight_template": {
            "judul": "Tren Inflow vs Outflow iBOSS",
            "insight": "Perbandingan inflow dan outflow harian menunjukkan gap yang perlu dimonitor.",
            "rekomendasi": "Sesuaikan kapasitas pemrosesan dengan rata-rata inflow harian.",
        },
        "intent_rules": {
            "insight_patterns": ["Tren inflow vs outflow iBOSS pada {period_count} periode."],
            "bullet_patterns": ["Terakhir: inflow {inflow_value}, outflow {outflow_value}."],
            "facts_to_use": ["series", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "custom"},
    },
    {
        "id": "iboss_funnel_kemacetan",
        "description": "iBOSS: Analisis bottleneck per tahapan proses (funnel)",
        "sql_template": IBOSS_FUNNEL_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
            "pilih_seksi": "Filter seksi (pemasukan/pengeluaran)",
        },
        "examples": ["Funnel iBOSS", "Bottleneck iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["funnel.*iboss", "bottleneck.*iboss", "kemacetan.*iboss"],
        "llm_label": "Analisis bottleneck iBOSS",
        "insight_template": {
            "judul": "Analisis Bottleneck iBOSS",
            "insight": "Funnel menunjukkan [TOTAL] dokumen yang mengalir antar tahapan dengan potensi kemacetan.",
            "rekomendasi": "Intervensi pada bottleneck utama untuk percepatan penyelesaian.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} tahapan funnel iBOSS."],
            "bullet_patterns": ["Tahapan teratas: {top_entity} = {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Bottleneck iBOSS", "columns": ["TAHAPAN_PROSES", "JUMLAH_DOKUMEN"]},
    },
    {
        "id": "iboss_rata_waktu_role",
        "description": "iBOSS: Rata-rata waktu penyelesaian per role/jabatan",
        "sql_template": IBOSS_RATA_WAKTU_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Rata-rata waktu iBOSS", "Waktu penyelesaian per role iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["waktu.*iboss", "durasi.*iboss", "penyelesaian.*iboss"],
        "llm_label": "Rata-rata waktu penyelesaian per role iBOSS",
        "insight_template": {
            "judul": "Rata-rata Waktu Penyelesaian per Role iBOSS",
            "insight": "Waktu penyelesaian bervariasi antar role, dengan [JABATAN] tertinggi di [RATA_WAKTU_MENIT] menit.",
            "rekomendasi": "Evaluasi efisiensi proses pada role dengan rata-rata waktu tertinggi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} role dengan data waktu penyelesaian."],
            "bullet_patterns": ["Role terlama: {top_entity} = {top_value} menit."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Rata-rata Waktu per Role iBOSS", "columns": ["JABATAN", "RATA_WAKTU_MENIT"]},
    },
    {
        "id": "iboss_kepatuhan_sla",
        "description": "iBOSS: Kepatuhan SLA permohonan (gauge)",
        "sql_template": IBOSS_KEPATUHAN_SLA_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["SLA iBOSS", "Kepatuhan SLA iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["sla.*iboss", "kepatuhan.*iboss", "iboss.*sla"],
        "llm_label": "Kepatuhan SLA iBOSS",
        "insight_template": {
            "judul": "Kepatuhan SLA iBOSS",
            "insight": "Capaian [GAUGE_KEPATUHAN_SLA] menggambarkan tingkat kepatuhan layanan iBOSS terhadap SLA 24 jam.",
            "rekomendasi": "Identifikasi dokumen yang melewati SLA untuk tindak lanjut prioritas.",
        },
        "intent_rules": {
            "insight_patterns": ["Kepatuhan SLA iBOSS: {gauge_kepatuhan_sla}."],
            "bullet_patterns": ["Skor SLA: {gauge_kepatuhan_sla}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Kepatuhan SLA iBOSS", "value_column": "GAUGE_KEPATUHAN_SLA"},
    },
    {
        "id": "iboss_leaderboard_sla",
        "description": "iBOSS: Leaderboard kepatuhan SLA per posisi dokumen",
        "sql_template": IBOSS_LEADERBOARD_SLA_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Leaderboard SLA iBOSS", "Ranking SLA iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["leaderboard.*iboss", "ranking.*sla.*iboss", "sla.*posisi.*iboss"],
        "llm_label": "Leaderboard kepatuhan SLA per posisi iBOSS",
        "insight_template": {
            "judul": "Leaderboard Kepatuhan SLA iBOSS",
            "insight": "Perbandingan kepatuhan SLA per posisi dokumen menunjukkan variasi kinerja antar unit.",
            "rekomendasi": "Fokus pada posisi dengan jumlah pelanggaran SLA tertinggi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} entri leaderboard SLA iBOSS."],
            "bullet_patterns": ["Posisi dengan pelanggaran terbanyak: {top_entity}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Leaderboard SLA iBOSS", "columns": ["POSISI_DOKUMEN", "TOTAL_DOKUMEN", "DOK_MEMENUHI_SLA", "DOK_MELEWATI_SLA"]},
    },
    {
        "id": "iboss_sebaran_overdue",
        "description": "iBOSS: Sebaran dokumen melewati SLA per posisi",
        "sql_template": IBOSS_SEBARAN_OVERDUE_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Sebaran overdue iBOSS", "Dokumen lewat SLA per posisi"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["sebaran.*overdue.*iboss", "overdue.*posisi.*iboss"],
        "llm_label": "Sebaran dokumen melewati SLA per posisi iBOSS",
        "insight_template": {
            "judul": "Sebaran Overdue iBOSS",
            "insight": "Distribusi dokumen overdue menunjukkan bottleneck di posisi [POSISI_DOKUMEN].",
            "rekomendasi": "Intervensi pada posisi dengan akumulasi overdue tertinggi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} posisi dengan dokumen overdue."],
            "bullet_patterns": ["Posisi terbanyak: {top_entity} = {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Sebaran Overdue iBOSS", "columns": ["POSISI_DOKUMEN", "DOKUMEN_MELEWATI_SLA"]},
    },
    {
        "id": "iboss_total_overdue",
        "description": "iBOSS: Total dokumen melewati SLA (historis)",
        "sql_template": IBOSS_TOTAL_OVERDUE_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Total overdue iBOSS", "Total lewat SLA iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["total.*overdue.*iboss", "seluruh.*sla.*iboss"],
        "llm_label": "Total dokumen melewati SLA iBOSS",
        "insight_template": {
            "judul": "Total Melewati SLA iBOSS",
            "insight": "Terdapat [TOTAL_MELEWATI_SLA] dokumen yang secara historis melewati SLA.",
            "rekomendasi": "Lakukan evaluasi menyeluruh terhadap proses yang berkontribusi pada pelanggaran SLA.",
        },
        "intent_rules": {
            "insight_patterns": ["{total_melewati_sla} dokumen melewati SLA iBOSS."],
            "bullet_patterns": ["Total: {total_melewati_sla}."],
            "facts_to_use": ["numeric", "filters", "row_count"],
        },
        "format_config": {"type": "single_value", "title": "Total Overdue iBOSS", "value_column": "TOTAL_MELEWATI_SLA"},
    },
    {
        "id": "iboss_proporsi_kerja",
        "description": "iBOSS: Komposisi waktu kerja staf (jam kerja vs di luar jam kerja)",
        "sql_template": IBOSS_PROPORSI_KERJA_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Proporsi kerja iBOSS", "Jam kerja staf iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["proporsi.*kerja.*iboss", "jam.*kerja.*iboss", "waktu.*kerja.*iboss"],
        "llm_label": "Komposisi waktu kerja staf iBOSS",
        "insight_template": {
            "judul": "Komposisi Waktu Kerja Staf iBOSS",
            "insight": "Proporsi jam kerja vs luar jam kerja mencerminkan beban kerja staf.",
            "rekomendasi": "Evaluasi distribusi beban kerja jika proporsi luar jam kerja tinggi.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} kategori waktu kerja iBOSS."],
            "bullet_patterns": ["Kategori terbanyak: {top_entity} = {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Komposisi Waktu Kerja iBOSS", "columns": ["KATEGORI_WAKTU", "JUMLAH_DOKUMEN"]},
    },
    {
        "id": "iboss_rapor_staf",
        "description": "iBOSS: Rapor evaluasi staf verifikator (skor akhir, performa, produktivitas, SLA)",
        "sql_template": IBOSS_RAPOR_STAF_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Rapor staf iBOSS", "Evaluasi verifikator iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["rapor.*iboss", "staf.*iboss", "verifikator.*iboss", "kinerja.*iboss"],
        "llm_label": "Rapor evaluasi staf verifikator iBOSS",
        "insight_template": {
            "judul": "Rapor Staf Verifikator iBOSS",
            "insight": "Skor akhir staf berkisar dengan rata-rata yang menunjukkan variasi kinerja.",
            "rekomendasi": "Gunakan data ini untuk program peningkatan kapasitas staf.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} staf iBOSS dievaluasi."],
            "bullet_patterns": ["Staf terbaik: {top_entity} skor {top_value}."],
            "facts_to_use": ["ranking", "filters", "row_count", "numeric"],
        },
        "format_config": {"type": "table", "title": "Rapor Staf iBOSS", "columns": ["NAMA_STAF", "SKOR_AKHIR", "NILAI_PERFORMA", "NILAI_PRODUKTIVITAS", "NILAI_SLA"]},
    },
    {
        "id": "iboss_detail_permohonan",
        "description": "iBOSS: Detail permohonan lengkap dengan histori proses per role",
        "sql_template": IBOSS_DETAIL_SQL,
        "params": {
            "rentang_waktu": "Filter rentang waktu",
            "pilih_tahun": "Filter tahun",
            "pilih_bulan": "Filter bulan",
            "pilih_role": "Filter role",
            "pilih_izin_iboss": "Filter kategori izin iBOSS",
        },
        "examples": ["Detail permohonan iBOSS", "Data lengkap iBOSS"],
        "active": True,
        "source": "iboss",
        "keyword_patterns": ["detail.*iboss", "data.*iboss", "tabel.*iboss", "permohonan.*iboss"],
        "llm_label": "Detail permohonan iBOSS",
        "insight_template": {
            "judul": "Detail Permohonan iBOSS",
            "insight": "Menampilkan [row_count] baris data permohonan iBOSS dengan histori proses.",
            "rekomendasi": "Gunakan filter untuk mempersempit pencarian berdasarkan periode atau status.",
        },
        "intent_rules": {
            "insight_patterns": ["{row_count} baris detail permohonan iBOSS."],
            "bullet_patterns": ["Total baris: {row_count}."],
            "facts_to_use": ["filters", "row_count"],
        },
        "format_config": {"type": "table", "title": "Detail Permohonan iBOSS", "columns": ["NO_DAFTAR", "NAMA_LAYANAN", "NAMA_PERUSAHAAN", "STATUS_IZIN", "STATUS_KEPATUHAN_SLA"]},
    },
]

# ── WRITE INTENTS ────────────────────────────────────────────────────────────

def main():
    with open(INTENTS_FILE, "r", encoding="utf-8") as f:
        existing = json.load(f)

    existing_ids = {i["id"] for i in existing}
    new_count = 0
    for intent in OSS_INTENTS + IBOSS_INTENTS:
        if intent["id"] not in existing_ids:
            existing.append(intent)
            existing_ids.add(intent["id"])
            new_count += 1
            print(f"  + {intent['id']}")
        else:
            print(f"  = {intent['id']} (already exists)")

    with open(INTENTS_FILE, "w", encoding="utf-8") as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\nDone. Added {new_count} new intents. Total: {len(existing)} intents.")

if __name__ == "__main__":
    main()
